24 create trip app
Lv-246Python/myTrip pull request #21
Opened 2017-07-18 08:22 UTC by PanLeon

## TRELLO

* [Main Trello ticket](https://trello.com/b/BJDdC443/mytrip)

## Code reviewers

- [ ] @Ashiato
- [ ] @black-art
- [ ] @hrytskivr
- [ ] @KarnaushenkoVO
- [ ] @PanLeon
- [ ] @spycheast
- [ ] @yuriiZherebukh

### Second Level Review

- [ ] @byshovets
- [ ] @lhalam

## Summary of issue

ToDo

## Summary of change

ToDo

## Testing approach

ToDo

## CHECK LIST
- [ ]  СI passed
- [ ]  Сode coverage >=90%
- [ ]  PR is reviewed manually again (to make sure you have 100% ready code)
- [ ]  All reviewers agreed to merge the PR
- [ ]  I've checked new feature as logged in and logged out user if needed
- [ ]  PR meets all conventions

2017-07-18 11:44 UTC, hrytskivr reviewed
See comments, have fun :)

2017-07-18 11:44 UTC, hrytskivr commented on myTrip/trip/models.py
>  from datetime import datetime
unicode_literals unused import?

2017-07-18 11:44 UTC, hrytskivr commented on myTrip/trip/models.py
> +from registration.models import CustomUser
use spaces to separate imports of diff type
https://www.python.org/dev/peps/pep-0008/#imports

2017-07-18 11:44 UTC, hrytskivr commented on myTrip/trip/models.py
> +        Returns the last 5 trips by the user
if you only need fixed '5' you should delete it from arguments
and replace word 'step' below into int '5'

or you could do a function get_trips, with which user can define himself how mych trips he needs back, and just set step=5 by default.

2017-07-18 11:44 UTC, hrytskivr commented on myTrip/trip/views.py
>          """Handles GET request"""
okay, but what exactly it does?

2017-07-18 11:44 UTC, hrytskivr commented on myTrip/trip/views.py
>          """Handles GET request"""
describe :)

2017-07-18 11:44 UTC, hrytskivr commented on myTrip/trip/views.py
> +            trips = Trip.get_trips(user_id)
what if there is no trips at all?

2017-07-18 11:44 UTC, hrytskivr commented on myTrip/tests/unittest/trip/test.py
> +    def test_get(self):
organize imports
rename tests for better understanding, the test name should be self-descriptive
add docstrings
"One test should only test one thing" - L.Halamaha

check this out: https://github.com/Lv-246Python/myTrip/blob/1e009c5af925530d3fd4f4ad513f9e7af96d6760/myTrip/tests/unittests/registration/test_models.py

2017-07-18 19:04 UTC, KarnaushenkoVO commented on myTrip/tests/unittest/trip/test.py
> +from django.test import TestCase, Client
you should split standart packages and your own packages by empy line

2017-07-18 19:15 UTC, KarnaushenkoVO commented on myTrip/tests/unittest/trip/test.py
> +        # trip = trip.to_dict()
this is bad comment

2017-07-18 19:16 UTC, KarnaushenkoVO commented on myTrip/tests/unittest/trip/test.py
> +
one test should test only one thing

2017-07-18 19:16 UTC, KarnaushenkoVO commented on myTrip/tests/unittest/trip/test.py
> +        self.assertEqual(response.status_code, 404)
one test should test only one thing

2017-07-18 19:17 UTC, KarnaushenkoVO commented on myTrip/trip/models.py
> +            "user": self.user.id,
must be "user_id"

2017-07-18 19:17 UTC, KarnaushenkoVO commented on myTrip/trip/models.py
> +                'user_id': user,
user_id or user, something one

2017-07-18 19:20 UTC, KarnaushenkoVO commented on myTrip/trip/models.py
> +        Returns the last 5 trips by the user
Liubomyr say to use step, this is right

2017-07-18 19:21 UTC, KarnaushenkoVO commented on myTrip/trip/views.py
> +            trips = Trip.get_trips(user_id)
filter will return empty queryset, all right

2017-07-19 06:52 UTC, oshtohryn submitted a review, later dismissed

2017-07-19 08:07 UTC, hrytskivr requested changes
Fix things mentioned in comments, i'll block merge for now(somehow it is available to merge whic is odd, whatever).

2017-07-19 08:25 UTC, lhalam reviewed
ToDo

2017-07-19 10:58 UTC, merged